#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Quantitative Analysis of Paleomagnetic Sampling Strategies  # The title of the book. Will be placed in the left navbar.
author                      : Facundo Sapienza  # The author of the book
copyright                   : "2023"  # Copyright year to be placed in the footer
logo                        : figures/logo.png  # A path to the book logo

execute:
  execute_notebooks: 'off'


# Binder support
# Information about where the book exists on the web
repository:
  url                       : https://github.com/PolarWandering/PaleoSampling
  branch                    : main  
  
launch_buttons:
  notebook_interface: "jupyterlab"
  
launch_buttons:
  binderhub_url: "https://mybinder.org/v2/gh/PolarWandering/PaleoSampling/HEAD"  # The URL for your BinderHub (e.g., https://mybinder.org)
  # colab_url: "https://colab.research.google.com"