#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title : Quantitative Analysis of Paleomagnetic Sampling Strategies
author : Facundo Sapienza
copyright : "2023"  
logo : figures/logo.png

execute:
 execute_notebooks: 'off'
 # allow_errors: false
 # exclude_patterns:
 # - '*Parallel*'
 # - '*Figure*'

repository:
 url : https://github.com/PolarWandering/PaleoSampling
 branch : main
html:
 use_repository_button: true
 use_issues_button: true
  
launch_buttons:
 notebook_interface: "jupyterlab"
  
launch_buttons:
 binderhub_url: "https://mybinder.org/v2/gh/PolarWandering/PaleoSampling/HEAD"
  # colab_url: "https://colab.research.google.com"
  
bibtex_bibfiles:
 - book/references.bib
