name: paleosampling
channels:
  - conda-forge
dependencies:
  - future
  - matplotlib
  - cartopy
  - wxpython
  - pandas
  - requests
  - jupyter
  - conda-forge::python-wget
  - seaborn
  - openpyxl
  - jupyter-book
  - scikit-learn
  - ipyparallel
  - distributed
  - ipywidgets
  - ca-certificates
  - certifi
  - openssl
  - pip: 
    - pmagpy==4.2.106
    # We install the modules for the sampling
    - -e ./smpsite